// <auto-generated />
using APIwebPET.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace APIwebPET.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20260713232919_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("APIwebPET.Models.Passageiro", b =>
                {
                    b.Property<long>("IdPassagem")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("IdPassagem");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("IdPassagem"));

                    b.Property<string>("DestinoViagem")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EmpresaParceira")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HoraDecolagem")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nome")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Sexo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Sobrenome")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TipoViagem")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdPassagem");

                    b.ToTable("Passageiros");
                });
#pragma warning restore 612, 618
        }
    }
}
